// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BeefService is an autogenerated mock type for the BeefService type
type BeefService struct {
	mock.Mock
}

// Count provides a mock function with given fields:
func (_m *BeefService) Count() map[string]int {
	ret := _m.Called()

	var r0 map[string]int
	if rf, ok := ret.Get(0).(func() map[string]int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	return r0
}

type mockConstructorTestingTNewBeefService interface {
	mock.TestingT
	Cleanup(func())
}

// NewBeefService creates a new instance of BeefService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBeefService(t mockConstructorTestingTNewBeefService) *BeefService {
	mock := &BeefService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
